<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.11">
  <compounddef id="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_network_protocol_e188125698c575255a18f4dd8d98568df" kind="class" language="Python" prot="public">
    <compoundname>NEAT_PyGenetics::NEAT::ErrorHandling::Exceptions::NetworkProtocolException::NetworkProtocolException</compoundname>
    <basecompoundref prot="public" virt="non-virtual">Exception</basecompoundref>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_network_protocol_e188125698c575255a18f4dd8d98568df_1a9d12de9b98da65c1a683fe038e066e49" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def NEAT_PyGenetics.NEAT.ErrorHandling.Exceptions.NetworkProtocolException.NetworkProtocolException.__init__</definition>
        <argsstring>(self, message, errors=None)</argsstring>
        <name>__init__</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>message</type>
          <defname>message</defname>
        </param>
        <param>
          <type>errors</type>
          <defname>errors</defname>
          <defval>None</defval>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="NEAT/ErrorHandling/Exceptions/NetworkProtocolException.py" line="2" column="1" bodyfile="NEAT/ErrorHandling/Exceptions/NetworkProtocolException.py" bodystart="2" bodyend="6"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="134">
        <label>NEAT_PyGenetics.NEAT.ErrorHandling.Exceptions.NetworkProtocolException.NetworkProtocolException</label>
        <link refid="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_network_protocol_e188125698c575255a18f4dd8d98568df"/>
        <childnode refid="135" relation="public-inheritance">
        </childnode>
      </node>
      <node id="135">
        <label>Exception</label>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="136">
        <label>NEAT_PyGenetics.NEAT.ErrorHandling.Exceptions.NetworkProtocolException.NetworkProtocolException</label>
        <link refid="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_network_protocol_e188125698c575255a18f4dd8d98568df"/>
        <childnode refid="137" relation="public-inheritance">
        </childnode>
      </node>
      <node id="137">
        <label>Exception</label>
      </node>
    </collaborationgraph>
    <location file="NEAT/ErrorHandling/Exceptions/NetworkProtocolException.py" line="1" column="1" bodyfile="NEAT/ErrorHandling/Exceptions/NetworkProtocolException.py" bodystart="1" bodyend="6"/>
    <listofallmembers>
      <member refid="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_network_protocol_e188125698c575255a18f4dd8d98568df_1a9d12de9b98da65c1a683fe038e066e49" prot="public" virt="non-virtual"><scope>NEAT_PyGenetics::NEAT::ErrorHandling::Exceptions::NetworkProtocolException::NetworkProtocolException</scope><name>__init__</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
