<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.11">
  <compounddef id="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_network_timeout_ex09d61843cecde07531bc3d1c6f238646" kind="class" language="Python" prot="public">
    <compoundname>NEAT_PyGenetics::NEAT::ErrorHandling::Exceptions::NetworkTimeoutException::NetworkTimeoutException</compoundname>
    <basecompoundref prot="public" virt="non-virtual">Exception</basecompoundref>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_network_timeout_ex09d61843cecde07531bc3d1c6f238646_1ac78b36042b085235de601a15a68ce98a" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def NEAT_PyGenetics.NEAT.ErrorHandling.Exceptions.NetworkTimeoutException.NetworkTimeoutException.__init__</definition>
        <argsstring>(self, message=&quot;&quot;, errors=None)</argsstring>
        <name>__init__</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>message</type>
          <defname>message</defname>
          <defval>&quot;&quot;</defval>
        </param>
        <param>
          <type>errors</type>
          <defname>errors</defname>
          <defval>None</defval>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="NEAT/ErrorHandling/Exceptions/NetworkTimeoutException.py" line="2" column="1" bodyfile="NEAT/ErrorHandling/Exceptions/NetworkTimeoutException.py" bodystart="2" bodyend="6"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="138">
        <label>NEAT_PyGenetics.NEAT.ErrorHandling.Exceptions.NetworkTimeoutException.NetworkTimeoutException</label>
        <link refid="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_network_timeout_ex09d61843cecde07531bc3d1c6f238646"/>
        <childnode refid="139" relation="public-inheritance">
        </childnode>
      </node>
      <node id="139">
        <label>Exception</label>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="140">
        <label>NEAT_PyGenetics.NEAT.ErrorHandling.Exceptions.NetworkTimeoutException.NetworkTimeoutException</label>
        <link refid="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_network_timeout_ex09d61843cecde07531bc3d1c6f238646"/>
        <childnode refid="141" relation="public-inheritance">
        </childnode>
      </node>
      <node id="141">
        <label>Exception</label>
      </node>
    </collaborationgraph>
    <location file="NEAT/ErrorHandling/Exceptions/NetworkTimeoutException.py" line="1" column="1" bodyfile="NEAT/ErrorHandling/Exceptions/NetworkTimeoutException.py" bodystart="1" bodyend="6"/>
    <listofallmembers>
      <member refid="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_network_timeout_ex09d61843cecde07531bc3d1c6f238646_1ac78b36042b085235de601a15a68ce98a" prot="public" virt="non-virtual"><scope>NEAT_PyGenetics::NEAT::ErrorHandling::Exceptions::NetworkTimeoutException::NetworkTimeoutException</scope><name>__init__</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
